gogoApp.constant('config', {
    url_basic: 'http://localhost:8080/api/v1/',
    url_site: 'site',
    info_anchor: '#/info',
    one_block_feed: 'feed',
    title: 'title',
    link: 'link',
    image: 'image',
    desc: 'desc',
    time: 'time',
    list: 'list',
    save_config: 'save',
    update_config: 'update',
    load_list: 'load_list',
    load_config: 'config/',
    delete_site: 'delete/',
    get_fileName: 'file/',
    download: 'download/'
});